contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #orthologymap channel"
    url: https://nfcore.slack.com/channels/orthologymap
    about: Discussion about the nf-core/orthologymap pipeline
